### ISSUE TITLE
Les vidéos ne s'ouvrent pas dans les principaux logiciels

### ISSUE THREAD

**Issue by justineemard** [a3lab/cavernes#2]
Les vidéos ont un format bizarre et ne s'ouvrent pas dans quicktime ni final cut.

**Comment by sofian** [comment]
@justineemard Can you try again now? I made some changes.

**Comment by justineemard** [comment]
Yes, this is perfect now ! Thank you Sofian !

**Comment by sofian** [comment]
Ok cool je ferme ce bug alors!
